### PR TITLE
Add Chinese Translation

### PR DESCRIPTION
**Pull request by Takanashi0301**
Hello, there is developer from China
Really thanks to you for write the plugins, it is so conveinient!
Hope there will be chinese language here!

### CODE REVIEW

**Comment by RitinhaUwU** [comment]
Thanks for reminding me that this branch even existed. You can always add the Chinese language to the translations file (ServerCommands.phrases.txt) if you want to @Takanashi0301

**Comment by RitinhaUwU** [comment]
As far as I know, the Portuguese part was already committed to the master branch, but go ahead and add more languages to it. Preferentially language you are fluent of or that you know well enough.

**Comment by Takanashi0301** [comment]
> Thanks for reminding me that this branch even existed. You can always add the Chinese language to the translations file (ServerCommands.phrases.txt) if you want to @Takanashi0301

oh, i got it, thanks for support! :)

**Comment by RitinhaUwU** [comment]
Closing this issue since I haven't got any feedback from the pull request author

**Pull request closed without merging**
